version: '3.1'

services: 

  localstack:
    container_name: localstack_main
    hostname: localstack
    image: localstack/localstack:1.3
    privileged: true
    environment: 
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - SERVICES=sqs,iam
      - EAGER_SERVICE_LOADING=1
      - PERSISTENCE=1
      # - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - USER=root
      - SQS_ENDPOINT_STRATEGY=path
    ports:
      - "${AWS_GATEWAY_PORT:-4566}:4566" # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    volumes: 
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"